### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715-labs-website#12]
- [x] please can we right align the nav bar (while keeping the logo left aligned)

- [x] At the bottom, quote is off right, please can we align with other text

- [x] At the very bottom, company details are extreme left, can we have left aligned as the main text

**Comment by rogerhutchings** [comment]
> please can we right align the nav bar (while keeping the logo left aligned)

not a problem, the nav bar was centred in the designs
