### ISSUE TITLE
Nav bar

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715-labs-website#13]
In addition to alignment (see other issue):

please can we reorder to match content (about to last place)

please can we rename "products" as "solutions" (also in the main content - will create new issue for that)

Please can we reduce the height by 1/3rd or so?  (It looks great on a big screen, and automatically changes on a really small screen, which is great, but we've found on some smaller screens not small enough to trigger the change in layout, it takes up a distractingly large proportion of screen area)

If you change the width of the window (from smallest to largest), is goes from:

menu drop d

- own (great)
- right aligned and not central height (think this is a mistake, can we remove? or is there a reason for this intermediate step that I've missed?)
- centre aligne

d (please can we update per the main text above)

**Comment by rogerhutchings** [comment]
cc #19
