### ISSUE TITLE
"in"

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715-labs-website#16]
There seems to be a rouge "In" (linked in logo?) at the bottom right of the web site

**Comment by rogerhutchings** [comment]
that's a link to the company linkedin page. the design originally had twitter as well, but we don't have an updated twitter feed (although I did just find out https://twitter.com/1715labs exists)

**Comment by rogerhutchings** [comment]
position was fixed in #12, if there's anything else to do with this feel free to re-open
