### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715-labs-website#17]
website seems to be less high res vs most recent image shared by Becky in Slack

(it's actually a different base image as well - with the big white blob near the very top in the latest becky image, but lower down on the website)

![image](https://user-images.githubusercontent.com/61154605/85013132-f6dc6280-b15b-11ea-892c-00aa2e8a8dac.png)

![image](https://user-images.githubusercontent.com/61154605/85013139-fba11680-b15b-11ea-8096-5e5459b86a01.png)

**Comment by rogerhutchings** [comment]
fixed in 3cc70849bdcc2f50605f6d9d9ed1eab3b4b435f7
