### ISSUE TITLE
How does 1715 Labs work?

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715-labs-website#18]
In the image flow, when the images are showing side by side (ie screen width not super narrow), please can we have arrows between each one?

something like 

![image](https://user-images.githubusercontent.com/61154605/85013650-d52fab00-b15c-11ea-8cd3-1b9d10672d51.png)

or 

![image](https://user-images.githubusercontent.com/61154605/85013658-d9f45f00-b15c-11ea-8edf-6524705a13f0.png)

whatever you think looks best

**Comment by colin1715labs** [comment]
to use arrows closer to Becky's version

**Comment by colin1715labs** [comment]
to include headers: 


Any data type
Maximise the human element
Structured data that makes a difference

**Comment by rogerhutchings** [comment]
site has been updated to a new design
