### ISSUE TITLE
Contact button

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715-labs-website#20]
One to discuss at 1:00pm (rather than action at this stage)

I love the contact us button: is the wording right?

- "Use the form below to drop us a line about your project." => "Use the form below to drop us a line about your data labelling needs." (or other?)
- "Hi! I have an idea for a project... "  => "Hi!  There might be something you can help me with..."

After we click submit,  would it be easy to put in a confirmation message? e.g. "message sent - thanks!  We will be in contact with you shortly."  could be reassuring the message was not lost into the ether :-)

Would it be easy / helpful to add validation to the email address - to avoid people making mistakes and us not being able to get in contact with them? (e.g. must have text before an @ symbol, and a TLD of at least 2 characters at the end)

If you write more than 2 lines it can be a bit hard to see what you're saying - is it easy to make the default height of the message box a little taller?

The form does not reset after submitting - perhaps just as the website's not live yet? (ie click the link and the content is still populated)

**Comment by rogerhutchings** [comment]
- Wording I just copied off the old contact form (mind you, I wrote that)

- Confirmation message is straightforward, but I'll add it in after launch

- The input is `type="email"`, so there is browser validation already; adding in validation as you type along can be a post-launch tweak

- Making it taller isn't a biggie

- Ooh, good catch; it does reset on cancel, but not submit

**Comment by rogerhutchings** [comment]
Closing due to #32
