### ISSUE TITLE
Buttons in general

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715-labs-website#21]
One to discuss at 1:00pm (rather than any action at this point):

Do we want the "learn more" button to jump down the page, or go to the contact form?

Do we want more "contact" (possibly worded differently on the button) lower down the page?  
e.g.:
-  under "How can 1715 Labs help your business?" section, something like "find out how 1715 Labs can support you"
-  under "Products" (aka "Solutions) section, something like "Ask us about your labelling needs"
-  under "Our story" something like "Say hi" 

Do we need a call to action button under "your name here" section?

**Comment by colin1715labs** [comment]
![image](https://user-images.githubusercontent.com/61154605/85019298-825af100-b166-11ea-94fa-3f25985371c6.png)

**Comment by rogerhutchings** [comment]
site has been updated to a new design
