### ISSUE TITLE
Add Slack integration

### ISSUE THREAD

**Issue by rogerhutchings** [1715labs/1715-labs-website#31]
One thing we've talked about recently is the ability for adding a chat widget hooked up to Slack so we can talk to visitors as and when they come in.

There's a few options out there:

- http://www.socialintents.com
- https://chatlio.com/
- https://www.intercom.com/integrations/slack
- https://hybrid.chat/live-chat-for-slack/
- https://www.getapp.com/customer-service-support-software/live-chat/w/slack/ (big list)

I have no strong feelings on which one we use; @colin1715labs, can you take a look and see what works for you? Once you've made a decision, I can add it

**Comment by colin1715labs** [comment]
Looks like intercom is the leading platform, and that we should be eligible for their start-up offer ($49 per month, which I think is 90% off for them), so I would probably err to that one as default.

But it looks like they pretty much can all do what we need at this point, so happy to go with any of them if you have a preference.

Thanks!
